### ISSUE TITLE
truffle migrate error

### ISSUE THREAD

**Issue by Federico2014** [weiyeli/block-chain-backend-Nodejs#1]
你好，我想学习你的代码，truffle compile 编译通过，但是 truffle migrate 运行时报错，能帮忙解决一下么
2_deploy_contracts.js
=====================
Error: Error: Could not find artifacts for ../contracts/PatientRec from any sources
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.31 (core: 5.0.31)
Node v10.16.2

**Comment by Federico2014** [comment]
即使路径改了，后面依然报错
2_deploy_contracts.js
=====================

   Deploying 'Ehealth'
   -------------------
Error: Error: Error:  *** Deployment Failed ***

"Ehealth" -- Invalid number of parameters for "undefined". Got 0 expected 3!.

    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.31 (core: 5.0.31)
Node v10.16.2

**Comment by Federico2014** [comment]
不知道这个参数怎么传递的

**Comment by Federico2014** [comment]
运行完npm install之后，再运行 npm start 还是报错

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../../m'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/a/projects/medicine/block-chain-backend-Nodejs/trr/routes/apis/member.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
